# -*- coding: utf-8 -*-
"""js_log.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5ef4NzC-MUm2L3YrETETDOH8sUdpP-z
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# data = open("/content/Tester_mlcneta.cs.wpi.edu%252Fmanifest_20000ms.mpd.log", "r").read()
df = pd.read_csv("/content/Tester_mlcneta.cs.wpi.edu%252Fmanifest_10000ms.mpd.log", sep="\n", names=['Params'])
df

log_df = df["Params"].str.extract(r"LOG  (?P<realtime_elapsed>\d+\.?\d*),(?P<current_time>\d+\.?\d*):(?P<fps>\d*),(?P<horizontal_resolution>\d+)x(?P<vert_res>\d*),(?P<bitrate>\d+),(?P<current_size_of_buffer>\d+\.?\d*)")
log_df = log_df.apply(pd.to_numeric)
log_df = log_df.dropna()
summary_df=log_df.describe()
summary_df

summary_fig = go.Figure(data=[go.Table(
    header=dict(values=list(summary_df.reset_index().columns),
                fill_color='paleturquoise',
                align='left'),
    cells=dict(values=summary_df.reset_index().T,
               fill_color='lavender',
               align='left'))
])
summary_fig.show()

fig = px.line(log_df, x="realtime_elapsed", y="current_size_of_buffer", title='realtime_elapsed vs current_size_of_buffer').update_layout(
    xaxis_title="realtime_elapsed(Sec)", yaxis_title="current_size_of_buffer(Sec)",xaxis_tickformat=',d'
)
fig.show()

