# -*- coding: utf-8 -*-
"""throughput.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iE8I-HGp7s50RSDtVNJXqs0hEnEl_hMN
"""

import pandas as pd
import plotly.express as px
import math
import os

# os.system("tshark -r", pcap_file, "-T fields -e ip.src -e frame.len -e     ip.proto -E separatorr=, -E occurrence=f >", csv_file)
df = pd.read_csv('filtered_packets_10sec.csv')

fig = px.line(df, x = 'Time', y = 'Length', title='graph')
fig.show()

"""# Preprocessing"""

df_new = df.iloc[:, [1,5]]

df_new

"""Grouping the bytes using seconds as unit"""

def grouping_attr(index):
  return math.floor(df_new['Time'].loc[index])

df_new=df_new.groupby(grouping_attr)['Length'].sum().reset_index()
df_new['Length'] = df_new['Length'].multiply(8e-6) #multiply to get Mbit/s
df_new

fig2 = px.line(df_new,x="index",y="Length",
        labels={
            "index":"Time(s)",
            "Length":"bitrate(Mbit/s)"
        }
           ,title='Throughput')
fig2.update_layout(showlegend=False)
fig2.show()